id: A45581898
title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
type: translation
pechas:
- IA6428EAF
- IA008BBF0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:31.169183
  last_modified_at: 2023-01-04 11:32:31.169188
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  IA6428EAF/10E9: E79F
  IA008BBF0/DDF0: E79F
